urls.py
'''from django.conf.urls import patterns, include, url
from django.conf.urls.defaults import *
from django.views.generic import TemplateView
from django.contrib import admin
admin.autodiscover()
# Uncomment the next two lines to enable the admin:
'''
'''from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()
'''
from django.conf.urls import patterns, include, url
from django.conf.urls.defaults import *
from django.views.generic import TemplateView
from django.contrib import admin
admin.autodiscover()
urlpatterns = patterns('',
    (r'^$', 'BuiltyMaker.main.views.index'),
    (r'^admin/', include(admin.site.urls)),
    (r'^accounts/', include('registration.urls')),
    (r'^main/', include('BuiltyMaker.main.urls')),
)

main/models.py
'''
    ** Including various required modules of django **
'''
from django.db import models
from django.forms import ModelForm,TextInput,ModelChoiceField
from django import forms
import datetime
from django.forms.fields import DateField, ChoiceField, MultipleChoiceField
from tagging.fields import TagField
from tagging.models import Tag
from django.contrib.sessions.models import Session
from django.contrib.auth.models import User
from django.db.models.signals import post_save
'''
   ** defination of models start from here **
'''

class fixed_values(models.Model):
    '''
       **  Model for fixed values of application **
    '''
    title = models.CharField(max_length = 500)
    owner = models.CharField(max_length = 100)
    serviceTax = models.FloatField()

class transfer_mode(models.Model):
	'''
		** Models for different transport modes **
	''' 
	mode = models.CharField(max_length = 50)
	
	def __unicode__(self):
		return self.mode

class dispatch_status(models.Model):
	'''
		** Model to be used in dispatch status of parcel **
	'''

	status = models.IntegerField(default = "0")
	date = models.DateField(null = True, blank = True)

class account(models.Model):
	'''
		** Model to add various transport componies **
	'''
	account = models.CharField(max_length = 100)
	
	def __unicode__(self):
		return self.account

class consignment_details(models.Model):
    '''
        ** Model for details of consignment **
    '''
    account_of = models.ForeignKey(account)
    consigner = models.CharField(max_length = 100)
    consigner_tin = models.CharField(max_length = 20)
    consignee = models.CharField(max_length = 100)
    consignee_tin = models.CharField(max_length = 20)
    source = models.CharField(max_length = 30)
    destination = models.CharField(max_length = 30)
    number_of_pkgs = models.IntegerField(max_length = 10)
    item_description = models.CharField(max_length = 200,blank=True)
    private_mark = models.CharField(max_length = 100,blank=True, default = "NA")
    invoice_no = models.CharField(max_length = 20, default = "NA")
    date = models.DateField()
    invoice_value = models.CharField(max_length = 30, default = "NA")
    actual_weight_in_kg = models.FloatField()
    charged_weight_in_kg = models.FloatField()
    service_tax_paid_by = models.CharField(max_length = 40,blank=True)
    mode_of_transfer = models.ForeignKey(transfer_mode)
    status = models.ForeignKey(dispatch_status)


class freight(models.Model):
    '''
        ** Model to define different freight modes. **
    '''
    mode = models.CharField(max_length = 100)
    def __unicode__(self):
                 return self.mode
class payment_details(models.Model):
    '''
        ** Model for payment details. **
    '''
    freight_mode = models.ForeignKey(freight)
    billing_station = models.CharField(max_length = 100)
    amount_to_pay = models.IntegerField(blank=True, default = 0)
    amount_paid = models.IntegerField(blank=True, default = 0)
    cheque_or_dd_no = models.CharField(max_length = 10,blank=True, default = "NA")


class freight_details(models.Model):
    '''
    ** Model for all freight details **
    '''
    cons = models.ForeignKey(consignment_details)
    pay = models.ForeignKey(payment_details)
    basic_freight = models.FloatField(blank=True, default = "0")
    barrier_charges = models.FloatField(blank=True, default = "0")
    hamali_charges = models.FloatField(blank=True, default = "0")
    stationary_charges = models.FloatField(blank=True, default = "0")
    other_charges = models.FloatField(blank=True, default = "0")
    total = models.FloatField()
    service_tax = models.FloatField()
    grand_total = models.FloatField()


class consignmentForm(forms.ModelForm):
    class Meta :
        model = consignment_details
        exclude = ['status']
        widgets = {
		'consigner': TextInput(attrs={'size':50}),
		'consignee' : TextInput(attrs={'size':50}),
		'source' : TextInput(attrs={'size':50}),
		'destination' : TextInput(attrs={'size':50}),
		'item_description' : TextInput(attrs={'size':50}),
		'private_mark': TextInput(attrs={'size':50}),
				}

class paymentDetailsForm(forms.ModelForm):
    class Meta:
        model = payment_details
        

class freightDetailsForm(forms.ModelForm):
    class Meta:
        model = freight_details
        exclude = ['cons','pay','total','service_tax','grand_total']

templates/backup/base-back.html
{% load admin_static %}{% load url from future %}<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
<title>{% block title %}{% endblock %}</title>
<link rel="stylesheet" type="text/css" href= "http://localhost/builtystatic/css/screen.css" />
{% block extrastyle %}{% endblock %}
<!--[if lte IE 7]><link rel="stylesheet" type="text/css" href="{% block stylesheet_ie %}{% static "admin/css/ie.css" %}{% endblock %}" /><![endif]-->
{% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% block stylesheet_rtl %}{% static "admin/css/rtl.css" %}{% endblock %}" />{% endif %}
<script type="text/javascript">window.__admin_media_prefix__ = "{% filter escapejs %}{% static "admin/" %}{% endfilter %}";</script>
{% block extrahead %}{% endblock %}
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}
</head>
<head>
<link rel="stylesheet" href="http://localhost/builtystatic/jquery-ui-1.10.3.custom/development-bundle/themes/redmond/jquery.ui.all.css">
	<script src="http://localhost/builtystatic/jquery-ui-1.10.3.custom/development-bundle/jquery-1.9.1.js"></script>
	<script src="http://localhost/builtystatic/jquery-ui-1.10.3.custom/development-bundle/ui/jquery.ui.core.js"></script>
	<script src="http://localhost/builtystatic/jquery-ui-1.10.3.custom/development-bundle/ui/jquery.ui.widget.js"></script>
	<script src="http://localhost/builtystatic/jquery-ui-1.10.3.custom/development-bundle/ui/jquery.ui.effect.js"></script>
	<script src="http://localhost/builtystatic/jquery-ui-1.10.3.custom/development-bundle/ui/jquery.ui.effect-blind.js"></script>
	<script src="http://localhost/builtystatic/jquery-ui-1.10.3.custom/development-bundle/ui/jquery.ui.effect-bounce.js"></script>
	<script src="http://localhost/builtystatic/jquery-ui-1.10.3.custom/development-bundle/ui/jquery.ui.effect-clip.js"></script>
	<script src="http://localhost/builtystatic/jquery-ui-1.10.3.custom/development-bundle/ui/jquery.ui.effect-drop.js"></script>
	<script src="http://localhost/builtystatic/jquery-ui-1.10.3.custom/development-bundle/ui/jquery.ui.effect-fold.js"></script>
	<script src="http://localhost/builtystatic/jquery-ui-1.10.3.custom/development-bundle/ui/jquery.ui.effect-slide.js"></script>
	<script src="http://localhost/builtystatic/jquery-ui-1.10.3.custom/development-bundle/ui/jquery.ui.datepicker.js"></script>
	<link rel="stylesheet" href="../demos.css">

<script>
$(function() {
$( "#id_date" ).datepicker({

changeMonth: true,
changeYear: true,dateFormat:'yy-mm-dd'
});
$( "#id_date" ).datepicker( "option", "showAnim", 'clip' );
});
  </script> 
</head>
{% load i18n %}

<body class="{% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %}">

<!-- Container -->
<div id="container">

    {% if not is_popup %}
    <!-- Header -->
    <div id="header">
        <div id="branding">
        {% block branding %}{% endblock %}
        </div>
       
        <div id="user-tools">
            {% trans 'Welcome' %}
            
            {% block userlinks %}
               
                <a href="builty/accounts/password/change">Change password</a> /
               
                <a href="builty/accounts/logout">{% trans 'Log out' %}</a>
            {% endblock %}
        </div>
        
        {% block nav-global %}{% endblock %}
    </div>
    <!-- END Header -->
    {% block breadcrumbs %}
    <div class="breadcrumbs">
    <a href="/builty">{% trans 'Home' %}</a>
    {% if title %} &rsaquo; {{ title }}{% endif %}
    </div>
    {% endblock %}
    {% endif %}

    {% block messages %}
        {% if messages %}
        <ul class="messagelist">{% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}</ul>
        {% endif %}
    {% endblock messages %}

    <!-- Content -->
    <div id="content" class="{% block coltype %}colM{% endblock %}">
        {% block pretitle %}{% endblock %}
        {% block content_title %}{% if title %}<h1>{{ title }}</h1>{% endif %}{% endblock %}
        {% block content %}
        {% block object-tools %}{% endblock %}
        {{ content }}
        {% endblock %}
        {% block sidebar %}{% endblock %}
        <br class="clear" />
    </div>
    <!-- END Content -->

    {% block footer %}<div id="footer"></div>{% endblock %}
</div>
<!-- END Container -->

</body>
</html>

templates/backup/base.html


{% load i18n %}
<html>
    <head>
        <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
        <script src="{{ LOCAL_URL }}/builtystatic/slider/playing/js/jquery.slides.min.js"></script>
      <!--  <link rel="stylesheet" href="{{ LOCAL_URL }}/builtystatic/slider/playing/style.css" /> -->
        <meta http-equiv="content-type" content="text/html;charset=utf-8" />
        <script type="text/javascript" src="{{ LOCAL_URL }}/builtystatic/js/jquery.js"></script>
        <script type="text/javascript" src="{{ LOCAL_URL }}/builtystatic/js/menu.js"></script>
        <link rel="stylesheet" href="{{ LOCAL_URL }}/builtystatic/jquery-ui-1.10.3.custom/development-bundle/themes/overcast/jquery.ui.all.css">
        <script src="{{ LOCAL_URL }}/builtystatic/jquery-ui-1.10.3.custom/development-bundle/jquery-1.9.1.js"></script>
        <script src="{{ LOCAL_URL }}/builtystatic/jquery-ui-1.10.3.custom/development-bundle/ui/jquery.ui.core.js"></script>
        <script src="{{ LOCAL_URL }}/builtystatic/jquery-ui-1.10.3.custom/development-bundle/ui/jquery.ui.widget.js"></script>
        <script src="{{ LOCAL_URL }}/builtystatic/jquery-ui-1.10.3.custom/development-bundle/ui/jquery.ui.button.js"></script>
        <script src="{{ LOCAL_URL }}/builtystatic/jquery-ui-1.10.3.custom/development-bundle/ui/jquery.ui.effect.js"></script>
        <script src="{{ LOCAL_URL }}/builtystatic/jquery-ui-1.10.3.custom/development-bundle/ui/jquery.ui.effect-clip.js"></script>
        <script src="{{ LOCAL_URL }}/builtystatic/jquery-ui-1.10.3.custom/development-bundle/ui/jquery.ui.datepicker.js"></script>
        <script>
            $(function() {
                  $('#slides').slidesjs({
                    width: 940,
                    height: 400,
                    play: {
                      active: true,
                      auto: true,
                      interval: 4000,
                      swap: true
                    }
                  });
                });
            
            $(function() {
            $( "#id_date" ).datepicker({
            
            changeMonth: true,
            changeYear: true,dateFormat:'yy-mm-dd'
            });
            $( "#id_date" ).datepicker( "option", "showAnim", 'clip' );
            });
            
            $(function() {
            		$( "button" )
            			.button()
            			.click(function( event ) {
            				event.preventDefault();
            			});
            	});
              
        </script> 
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
        <meta charset="utf-8"/>
        <meta name="description" content="">
        <meta name="author" content="">
        <title>Builty Maker</title>
        <link rel="stylesheet" type="text/css" media="screen" href="{{ LOCAL_URL }}/builtystatic/css/main.css" />
        <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
    </head>
    <body>
        {% block nav-main %}
        <div class="wrap">
            <div id="logo">
                <h1><a href="/builty/" title="Home">Open Freight Carriers</a></h1>
            </div>
            <div id="options">
                <h3><a href="/builty/accounts/password/change/" data-role="button">{% trans 'Change Password' %}</a></h3>
                <h3><a href="/builty/accounts/logout">{% trans 'Log out' %}</a></h3>
            </div>
            <ul id="nav">
                <li>
                    <h3><a href="/builty/main/newconsignment/"  accesskey="n"><span class="akey">N</span>ew Consignment</a></h3>
                </li>
                <li>
                    <h3><a href="/builty/main/cons_register/" accesskey="c"><span class="akey">C</span>onsignment Register</a></h3>
                </li>
                <li>
                    <h3><a href="/builty/main/prev_cons/" accesskey="p"><span class="akey">P</span>revious Consignment</a></h3>
                </li>
            </ul>
        </div>
        <!-- /menu -->
        {% endblock %}
        {% block columnwrap %}
        <div class="wrap">
            {% block content %}
            {% endblock %}
        </div>
        {% endblock %}
        <!-- END content -->
    </body>
</html>



templates/backup/base1.html
{% load admin_static %}{% load url from future %}<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
<title>{% block title %}{% endblock %}</title>
<link rel="stylesheet" type="text/css" href= "http://localhost/media/css/base.css" />
{% block extrastyle %}{% endblock %}
<!--[if lte IE 7]><link rel="stylesheet" type="text/css" href="{% block stylesheet_ie %}{% static "admin/css/ie.css" %}{% endblock %}" /><![endif]-->
{% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% block stylesheet_rtl %}{% static "admin/css/rtl.css" %}{% endblock %}" />{% endif %}
<script type="text/javascript">window.__admin_media_prefix__ = "{% filter escapejs %}{% static "admin/" %}{% endfilter %}";</script>
{% block extrahead %}{% endblock %}
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}
</head>
{% load i18n %}

<body class="{% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %}">

<!-- Container -->
<div id="container">

    {% if not is_popup %}
    <!-- Header -->
    <div id="header">
        <div id="branding">
        {% block branding %}{% endblock %}
        </div>
        
        {% block nav-global %}{% endblock %}
    </div>
    <!-- END Header -->
    {% block breadcrumbs %}
    <div class="breadcrumbs">
    <a href="/builty">{% trans 'Home' %}</a>
    {% if title %} &rsaquo; {{ title }}{% endif %}
    </div>
    {% endblock %}
    {% endif %}

    {% block messages %}
        {% if messages %}
        <ul class="messagelist">{% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}</ul>
        {% endif %}
    {% endblock messages %}

    <!-- Content -->
    <div id="content" class="{% block coltype %}colM{% endblock %}">
        {% block pretitle %}{% endblock %}
        {% block content_title %}{% if title %}<h1>{{ title }}</h1>{% endif %}{% endblock %}
        {% block content %}
        {% block object-tools %}{% endblock %}
        {{ content }}
        {% endblock %}
        {% block sidebar %}{% endblock %}
        <br class="clear" />
    </div>
    <!-- END Content -->

    {% block footer %}<div id="footer"></div>{% endblock %}
</div>
<!-- END Container -->

</body>
</html>

templates/backup/base_consNote.html
{% load admin_static %}{% load url from future %}<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
<title>{% block title %}{% endblock %}</title>
<link rel="stylesheet" type="text/css" href= "http://localhost/builtystatic/css/screen.css" />
{% block extrastyle %}{% endblock %}
<!--[if lte IE 7]><link rel="stylesheet" type="text/css" href="{% block stylesheet_ie %}{% static "admin/css/ie.css" %}{% endblock %}" /><![endif]-->
{% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% block stylesheet_rtl %}{% static "admin/css/rtl.css" %}{% endblock %}" />{% endif %}
<script type="text/javascript">window.__admin_media_prefix__ = "{% filter escapejs %}{% static "admin/" %}{% endfilter %}";</script>
{% block extrahead %}{% endblock %}
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}
</head>
<head>
<link rel="stylesheet" href="{{ LOCAL_URL }}/~jass/jquery-ui-1.10.3.custom/css/redmond/jquery-ui-1.10.3.custom.css" />
<script src="{{ LOCAL_URL }}/~jass/jquery-ui-1.10.3.custom/js/jquery-ui-1.10.3.custom.min.js">
</script>
<script src="{{ LOCAL_URL }}/~jass/jquery-ui-1.10.3.custom/js/jquery-ui-1.10.3.custom.js"></script>

<script>
$(function() {
$( "#id_date" ).datepicker({

changeMonth: true,
changeYear: true,dateFormat:'yy-mm-dd'
});
$( "#id_date" ).datepicker( "option", "showAnim", 'clip' );
});
  </script> 
</head>
{% load i18n %}

<body class="{% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %}">

<!-- Container -->
<div id="container">

    {% if not is_popup %}
    <!-- Header -->
    <div id="header">
        <div id="branding">
        {% block branding %}{% endblock %}
        </div>
       
        <div id="user-tools">
            {% trans 'Welcome' %}
            <strong>{% filter force_escape %}{% firstof user.first_name user.username %}{% endfilter %}</strong>
            {% block userlinks %}
               
                <a href="builty/accounts/password/change">Change password</a> /
               
                <a href="builty/accounts/logout">{% trans 'Log out' %}</a>
            {% endblock %}
        </div>
        
        {% block nav-global %}{% endblock %}
    </div>
    <!-- END Header -->
    {% block breadcrumbs %}
    <div class="breadcrumbs">
    
    {% if title %} &rsaquo; {{ title }}{% endif %}
    </div>
    {% endblock %}
    {% endif %}

    {% block messages %}
        {% if messages %}
        <ul class="messagelist">{% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}</ul>
        {% endif %}
    {% endblock messages %}

    <!-- Content -->
    <div id="content" class="{% block coltype %}colM{% endblock %}">
        {% block pretitle %}{% endblock %}
        {% block content_title %}{% if title %}<h1>{{ title }}</h1>{% endif %}{% endblock %}
        {% block content %}
        {% block object-tools %}{% endblock %}
        {{ content }}
        {% endblock %}
        {% block sidebar %}{% endblock %}
        <br class="clear" />
    </div>
    <!-- END Content -->

    {% block footer %}<div id="footer"></div>{% endblock %}
</div>
<!-- END Container -->

</body>
</html>

templates/backup/base_site.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{{ title }} {% trans 'Builty Maker' %}{% endblock %}

{% block branding %}
<h1 id="site-name">{% trans 'Builty Maker' %}</h1>
{% endblock %}

{% block nav-global %}{% endblock %}

templates/backup/base_site1.html
{% extends "base1.html" %}
{% load i18n %}

{% block title %}{{ title }} {% trans 'Builty Maker' %}{% endblock %}

{% block branding %}
<h1 id="site-name">{% trans 'Builty Maker' %}</h1>
{% endblock %}

{% block nav-global %}{% endblock %}

templates/backup/base_site_consNote.html
{% extends "base_consNote.html" %}
{% load i18n %}



{% block branding %}
{% endblock %}

{% block nav-global %}{% endblock %}